name: Build and deploy to github pages
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2

      - name: Get the latest release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: 'danielpancake-website-gen-x86_64_linux'

      - name: Generate website
        run: |
          chmod +x ./danielpancake-website-gen-x86_64_linux
          ./danielpancake-website-gen-x86_64_linux rebuild -v

      - name: Install HTML tidy
        run: |
          sudo apt-get install tidy

      - name: Tidy HTML
        continue-on-error: true
        # exit code 1 returned by tidy on warns upsets the workflow 
        run: |
          cd _site
          tidy -utf8 -imq -w 170 --tidy-mark no index.html 2> /dev/null

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: danielpancake-pages
          folder: _site
          clean: true
