name: Build and deploy to github pages
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cabal: ["3.10.1.0"]
        ghc: ["9.4.4"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cabal Update
        run: |
          cabal update
          cabal freeze $CONFIG

      - name: Cache Cabal
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Build Site
        run: |
          cabal build $CONFIG
          cabal run site rebuild

      - name: Install HTML tidy
        run: |
          sudo apt-get install tidy

      - name: Tidy HTML
        run: |
          cd _site
          tidy -utf8 -imq -w 170 --tidy-mark no index.html 2> /dev/null

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: danielpancake-pages
          folder: _site
          clean: true
